#case_data/api/api_config.yaml
Crud:
  detail:
    pageCode: "2023060819591966723041"
    recordId: "11651379"
    type: "detail"

  submit:
    pageCode: "2024083017002443504002"
    pushOrigin: 1
    fieldData:
      wenben__c: "增加"
      shuzhi__c: 1.1
      danxuan__c:
        name: "选项1"
        value: "选项1"
      duoxuan__c:
        - name: "选项1"
          value: "选项1"
          style:
            color: "#66CC00"
            background: "#F0FAE5"
        - name: "选项2"
          value: "选项2"
          style:
            color: "#007EFF"
            background: "#E5F2FF"
      riqi1__c: "2024-12-05"

  delete:
    recordIds:
      - 1607717

  edit:
    pageCode: "2024083017002443504002"
    pushOrigin: 1
    fieldData:
      wenben__c: "增加"

  list:
    viewCode: "2023060819591966214452"
    pageCode: "2023060819591966712110"
    page: 1
    filterCriteriaList: []
    num: 20
    filter: []

CalendarPromptLightAPI:
  list:
    formCode: "yxpm__CustomObject0148__c"
    viewCode: "2023060819591966214452"
    pageCode: "2024011809413782107952"
    queryCriteria:
      riqi1__c:
        - "2023-08-01"
        - "2023-08-31"
    currentPos: null
    calendarField: "riqi1__c"
    filterCriteria:
      -
        -
          objectType: "form"
          objectId: "164341"
          fieldKey: "wenben__c"
          fieldName: "文本"
          fieldType: "text"
          subFieldKey: null
          subFieldType: null
          subFieldName: null
          conditionType: "equal"
          refValues:
            - objectType: "form"
              objectId: null
              fieldKey: null
              fieldName: null
              fieldType: null
              fieldTypeLabel: null
              subFieldKey: null
              subFieldType: null
              subFieldName: null
              subFieldTypeLabel: null
              constant: true
              constantValue: "1"
              function: null
              path: null
              lastFieldType: null
              lastFieldName: null
              lastFieldTypeLabel: null
          useFormId: null
          path: null
          lastFieldType: null
          lastFieldName: null
          lastFieldTypeLabel: null

RecordList:
  list:
    viewCode: "wenbenfeikong"
    pageCode: "2023060819591966712110"
    page: 1
    num: 10
    filter: []

BusinessRule:
  list:
    isEnable: 1

Formula:
  data:
    expressions:
      dangqianyonghusuozaizuzhi__c: " ##CURRENTORG## ()"
    preData:
      - dangqianyonghusuozaizuzhi__c: []
